name: Pipeline

on: [push]

jobs:
  generate_environment_variables:
    runs-on: ubuntu-latest
    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3.0
        with:
          envkey_DEBUG: true
          envkey_GOOGLE_EMAIL: ${{ secrets.GOOGLE_EMAIL }}
          envkey_GOOGLE_KEY: ${{ secrets.GOOGLE_KEY }}
          envkey_GOOGLE_SHEET: ${{ secrets.GOOGLE_SHEET }}
          envkey_SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
          envkey_SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          envkey_SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
          file_name: .env
          fail_on_empty: true
      - name: Log job
        run: |
          echo "The run id is: $GITHUB_RUN_ID" 
          echo "The GitHub Actor's username is: $GITHUB_ACTOR"
          echo "The API key is:${{secrets.GOOGLE_EMAIL}}"
  test_file:
    runs-on: ubuntu-latest
    steps:
      - name: Verify directory
        uses: ./
      - name: Verify if has file
        run: |
          ls -la
